### ISSUE TITLE
option to change between files / database precedence [improvement]

### ISSUE THREAD

**Issue by Cyrille37** [Waavi/translation#35]
Hi,

Actually the documentation say _entries found in the filesystem take precedence over the database_. It should be nice to inverse this spec because living translations should be in database but the application need default values in files.

And perhaps changing between behaviors with an configuration option ;-)

Cheers.

**Comment by sildraug** [comment]
Hi,

This is because reading from both the database and the filesystem is not recommended in a production environment. The recommended way is use the database setting and load your translation files into the database when pushing code into production using the provided artisan commad:

php artisan translator:load

Best!
