### ISSUE TITLE
Problem translating attributes

### ISSUE THREAD

**Issue by cmaerz** [Waavi/translation#76]
Got this in my translation file (validation.php):
```
'attributes' => [
        'nick' => 'Nickname',
        'passwd' => 'Passwort',
],
```

this is imported in my database:
group: validation item: attributes.nick 

But in my error messages its not resolved. Is there an error on my side or are attribute translations not supported?

**Comment by sildraug** [comment]
Because of how the validator works, I believe the attributes do not work.

**Comment by AEzazi** [comment]
how repair it?

**Comment by nermion** [comment]
you can try something like this:
    'custom' => [
        'nick' => [
            'required' => 'You must choose a nickname.',
        ],

that will work. Trying to set attributes did not work for me either so I tried custom and it worked.

**Comment by jeremyargoud** [comment]
Hello,

To solve the problem, I had to use array_set helper in loaders.

In FileLoader.php:

```
public function loadSource($locale, $group, $namespace = '*')
{
    $result = [];
    foreach (array_dot($this->laravelFileLoader->load($locale, $group, $namespace)) as $key => $value) {
        array_set($result, $key, $value);
    }
    return $result;
}
```

In DatabaseLoader.php:

```
public function loadSource($locale, $group, $namespace = null)
{
    $result = [];
    foreach ($this->translationRepository->loadSource($locale, $namespace, $group) as $key => $value) {
        array_set($result, $key, $value);
    }
    return $result;
}
```

Now attributes are correctly translated for me :-)

**Comment by sildraug** [comment]
The issue is with the method **getAttributeFromTranslations** in **Illuminate\Validation\Concerns\FormatsMessages**. It expects trans('validation.attributes') to be an array, but because our translator flattens the content of the validation file, validation.attributes is just empty in our case.

@jeremyargoud's solution works because it goes from dot notation to multi-dimensional array when loading from the Database.

Version 2.2.1 fixes this issue.
