### ISSUE TITLE
Using unstable while loading translations from database

### ISSUE THREAD

**Issue by ersoypembe** [Waavi/translation#90]
Hi;

As far as I see; while loading translations from database 'loadSource' method is called and there is no criteria for unstable/stable column. Let's say **en** is my primary locale and **it** is secondary locale. But when i load translations for secondary locale(authenticated user's locale for example) and there are some unstable keys for this secondary locale, then it shouldn't be loaded right ? Instead primary locale's translation should be loaded. Am I missing something ? 

Great package by the way (congrats)

**Comment by sildraug** [comment]
@ersoypembe This is an undocumented feature. When you edit a text entry in the default locale (through TranslationRepository@update, updateAndLock or loadArray), all translations for that entry are marked as "unstable", meaning they might not be accurate anymore since the source text has changed.

It is up to your app what to do with this.
